# Generated by Django 5.2.12 on 2026-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_activitylog'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='accounts_ac_user_id_3418de_idx',
            old_name='accounts_ac_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='activitylog',
            new_name='accounts_ac_branch__2dff62_idx',
            old_name='accounts_ac_branch_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name="To'liq ism"),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan"),
        ),
    ]
