# Generated by Django 5.2.12 on 2026-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_add_smstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsreminder',
            name='inspection_type',
            field=models.CharField(choices=[('technical', "Texnik ko'rik"), ('gas_cylinder', 'Gaz ballon akt')], default='technical', max_length=20, verbose_name="Ko'rik turi"),
        ),
        migrations.AddField(
            model_name='smstemplate',
            name='inspection_type',
            field=models.CharField(choices=[('technical', "Texnik ko'rik"), ('gas_cylinder', 'Gaz ballon akt'), ('any', 'Har ikkisi')], default='any', max_length=20, verbose_name="Ko'rik turi"),
        ),
    ]
