# Generated by Django 5.2.12 on 2026-07-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsreminder',
            name='infinireach_message_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='InfiniReach Message ID'),
        ),
    ]
