# Generated by Django 5.2.12 on 2026-07-16 12:23
# This migration is a no-op because infinireach_message_id was already added in 0003

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_noop'),
    ]

    operations = [
    ]
