# Generated by Django 5.2.12 on 2026-09-21 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_default_branch_data'),
        ('reminders', '0008_smsreminder_infinireach_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smstemplate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Shablon nomi'),
        ),
        migrations.AddConstraint(
            model_name='smstemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'name'), name='unique_active_smstemplate_branch_name'),
        ),
    ]
