# Generated by Django 5.2.12 on 2026-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_add_amount_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspection',
            options={'ordering': ['-inspection_date', '-created_at'], 'verbose_name': "Ko'rik", 'verbose_name_plural': "Ko'riklar"},
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspection_type',
            field=models.CharField(choices=[('technical', "Texnik ko'rik"), ('gas_cylinder', 'Gaz ballon akt')], default='technical', max_length=20, verbose_name="Ko'rik turi"),
        ),
    ]
