# Generated by Django 5.2.12 on 2026-09-21 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_default_branch_data'),
        ('payments', '0002_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='branches.branch', verbose_name='Filial'),
        ),
    ]
