# Generated by Django 5.2.12 on 2026-07-13 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-created_at'], 'verbose_name': 'Avtomobil', 'verbose_name_plural': 'Avtomobillar'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gas_cylinder_expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Gaz ballon akt muddati'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='engine_type',
            field=models.CharField(choices=[('gasoline', 'Benzin'), ('diesel', 'Dizel'), ('electric', 'Elektr'), ('hybrid', 'Gibrid'), ('gas', 'Gaz'), ('metan', 'Metan (CNG)'), ('propan', 'Propan (LPG)')], default='gasoline', max_length=20, verbose_name='Dvigatel turi'),
        ),
    ]
