# Generated by Django 5.2.12 on 2026-07-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mijoz', 'verbose_name_plural': 'Mijozlar'},
        ),
    ]
